baseurl = "https://sad-sinss.netlify.app/"
title = "Sad-Sinss"
copyright = "Copyright &copy; 2020 - Insecupa"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Insecupa"

[params]
    tagline = "Writing what comes."

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"